config/routes.rb
Rails.application.routes.draw do
  resources :mecanico_especialidads
  resources :especialidads
  resources :mecanicos
  resources :autos
  
  root :to => 'inicio#index'
  get 'inicio/index'

  devise_for :usuarios

end

app/models/mecanico_especialidad.rb
class MecanicoEspecialidad < ActiveRecord::Base
  belongs_to :mecanico
  belongs_to :especialidad
end

app/controllers/mecanico_especialidads_controller.rb
class MecanicoEspecialidadsController < ApplicationController
  before_action :set_mecanico_especialidad, only: [:show, :edit, :update, :destroy]

  # GET /mecanico_especialidads
  # GET /mecanico_especialidads.json
  def index
    @mecanico_especialidads = MecanicoEspecialidad.all
  end

  # GET /mecanico_especialidads/1
  # GET /mecanico_especialidads/1.json
  def show
  end

  # GET /mecanico_especialidads/new
  def new
    @mecanico_especialidad = MecanicoEspecialidad.new
  end

  # GET /mecanico_especialidads/1/edit
  def edit
  end

  # POST /mecanico_especialidads
  # POST /mecanico_especialidads.json
  def create
    @mecanico_especialidad = MecanicoEspecialidad.new(mecanico_especialidad_params)

    respond_to do |format|
      if @mecanico_especialidad.save
        format.html { redirect_to @mecanico_especialidad, notice: 'Mecanico especialidad was successfully created.' }
        format.json { render :show, status: :created, location: @mecanico_especialidad }
      else
        format.html { render :new }
        format.json { render json: @mecanico_especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mecanico_especialidads/1
  # PATCH/PUT /mecanico_especialidads/1.json
  def update
    respond_to do |format|
      if @mecanico_especialidad.update(mecanico_especialidad_params)
        format.html { redirect_to @mecanico_especialidad, notice: 'Mecanico especialidad was successfully updated.' }
        format.json { render :show, status: :ok, location: @mecanico_especialidad }
      else
        format.html { render :edit }
        format.json { render json: @mecanico_especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mecanico_especialidads/1
  # DELETE /mecanico_especialidads/1.json
  def destroy
    @mecanico_especialidad.destroy
    respond_to do |format|
      format.html { redirect_to mecanico_especialidads_url, notice: 'Mecanico especialidad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mecanico_especialidad
      @mecanico_especialidad = MecanicoEspecialidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mecanico_especialidad_params
      params.require(:mecanico_especialidad).permit(:mecanico_id, :especialidad_id)
    end
end

app/helpers/mecanico_especialidads_helper.rb
module MecanicoEspecialidadsHelper
end

app/views/mecanico_especialidads/_form.html.erb
<%= form_for(@mecanico_especialidad) do |f| %>
  <% if @mecanico_especialidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mecanico_especialidad.errors.count, "error") %> prohibited this mecanico_especialidad from being saved:</h2>

      <ul>
      <% @mecanico_especialidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mecanico_id %><br>
    <%= f.select("mecanico_id",Mecanico.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Seleccione Mecanico'}) %>
  </div>
  <div class="field">
    <%= f.label :especialidad_id %><br>
    <%= f.select("especialidad_id",Especialidad.all.collect{|l| [ l.espnombre, l.id ] }, {include_blank: 'Seleccione Especialidad'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mecanico_especialidads/edit.html.erb
<div class="panel panel-success">
<h1>EDITAR MECANICO Y SU ESPECIALIDAD</h1>

<%= render 'form' %>

<%= link_to 'MOSTRAR', @mecanico_especialidad %> |
<%= link_to 'ATRAS', mecanico_especialidads_path %>
</div>

app/views/mecanico_especialidads/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-success">
<h1>LISTA DE MECANICOS Y SU ESPECIALIDAD</h1>

<table class=" table table-bordered table-hover">
  <thead>
    <tr>
      <th>MECANICO</th>
      <th>ESPECIALIDAD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mecanico_especialidads.each do |mecanico_especialidad| %>
      <tr>
        <td><%= mecanico_especialidad.mecanico %></td>
        <td><%= mecanico_especialidad.especialidad %></td>
        <td><%= link_to 'MOSTRAR', mecanico_especialidad %></td>
        <td><%= link_to 'EDITAR', edit_mecanico_especialidad_path(mecanico_especialidad) %></td>
        <td><%= link_to 'ELIMINAR', mecanico_especialidad, method: :delete, data: { confirm: 'SE ELIMINARA COMPLETAMENTE' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'NUEVO MECANICO Y SU ESPECIALIDAD', new_mecanico_especialidad_path %>
</div>

app/views/mecanico_especialidads/new.html.erb
<div class="panel panel-success">
<h1>CREAR MECANICO Y SU ESPECIALIDAD</h1>

<%= render 'form' %>

<%= link_to 'ATRAS', mecanico_especialidads_path %>
</div>

app/views/mecanico_especialidads/show.html.erb
<div class="panel panel-success">
<p id="notice"><%= notice %></p>

<p>
  <strong>MECANICO:</strong>
  <%= @mecanico_especialidad.mecanico %>
</p>

<p>
  <strong>ESPECIALIDAD:</strong>
  <%= @mecanico_especialidad.especialidad %>
</p>

<%= link_to 'EDITAR', edit_mecanico_especialidad_path(@mecanico_especialidad) %> |
<%= link_to 'ATRAS', mecanico_especialidads_path %>
</div>