config/routes.rb
Rails.application.routes.draw do
  resources :mecanico_especialidads
  resources :especialidads
  resources :mecanicos
  resources :autos
  
  root :to => 'inicio#index'
  get 'inicio/index'

  devise_for :usuarios

end

app/views/shared/_alert.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">INICIO</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

          <% if usuario_signed_in? %>
          <li><a href="<%= autos_path %>">Tus Autos</a></li>
          <li><a href="<%= mecanicos_path %>">Mecanicos</a></li>
          <li><a href="<%= especialidads_path %>">Especialidad</a></li>
          <li><a href="<%= mecanico_especialidads_path %>">Mecanico/Especialistas</a></li>
        <% end %>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a> <%= current_usuario.email %> </a></li>
        	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
        <% else %>
        	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>