config/routes.rb
Rails.application.routes.draw do
  resources :mecanico_especialidads
  resources :especialidads
  resources :mecanicos
  resources :autos
  
  root :to => 'inicio#index'
  get 'inicio/index'

  devise_for :usuarios

end

app/models/mecanico.rb
class Mecanico < ActiveRecord::Base
  has_many :mecanico_especialidad
  has_many :especialidad, :through => :mecanico_especialidad
  has_many :auto
  validates :nombre, presence:   true
  validates :apellido, presence: true
end

app/controllers/mecanicos_controller.rb
class MecanicosController < ApplicationController
  before_action :set_mecanico, only: [:show, :edit, :update, :destroy]

  # GET /mecanicos
  # GET /mecanicos.json
  def index
    @mecanicos = Mecanico.all
  end

  # GET /mecanicos/1
  # GET /mecanicos/1.json
  def show
    @especialidads =  @mecanico.especialidad.all

  end

  # GET /mecanicos/new
  def new
    @mecanico = Mecanico.new
  end

  # GET /mecanicos/1/edit
  def edit
  end

  # POST /mecanicos
  # POST /mecanicos.json
  def create
    @mecanico = Mecanico.new(mecanico_params)

    respond_to do |format|
      if @mecanico.save
        format.html { redirect_to @mecanico, notice: 'Mecanico was successfully created.' }
        format.json { render :show, status: :created, location: @mecanico }
      else
        format.html { render :new }
        format.json { render json: @mecanico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mecanicos/1
  # PATCH/PUT /mecanicos/1.json
  def update
    respond_to do |format|
      if @mecanico.update(mecanico_params)
        format.html { redirect_to @mecanico, notice: 'Mecanico was successfully updated.' }
        format.json { render :show, status: :ok, location: @mecanico }
      else
        format.html { render :edit }
        format.json { render json: @mecanico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mecanicos/1
  # DELETE /mecanicos/1.json
  def destroy
    @mecanico.destroy
    respond_to do |format|
      format.html { redirect_to mecanicos_url, notice: 'Mecanico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mecanico
      @mecanico = Mecanico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mecanico_params
      params.require(:mecanico).permit(:nombre, :apellido)
    end
end

app/helpers/mecanicos_helper.rb
module MecanicosHelper
end

app/views/mecanicos/_form.html.erb
<%= form_for(@mecanico) do |f| %>
  <% if @mecanico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mecanico.errors.count, "error") %> prohibited this mecanico from being saved:</h2>

      <ul>
      <% @mecanico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mecanicos/edit.html.erb
<div class="panel panel-success">
<h1>Modificar datos del Mecanico</h1>

<%= render 'form' %>

<%= link_to 'MOSTRAR', @mecanico %> |
<%= link_to 'ATRAS', mecanicos_path %>
</div>

app/views/mecanicos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
<h1>Lista de Mecanicos</h1>
</div>
<div class="panel panel-success">
<table class=" table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @mecanicos.each do |mecanico| %>
      <tr>
        <td><%= mecanico.nombre %></td>
        <td><%= mecanico.apellido %></td>
        <td><%= link_to 'Show', mecanico %></td>
        <td><%= link_to 'Edit', edit_mecanico_path(mecanico) %></td>
        <td><%= link_to 'Destroy', mecanico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingrese nuevo Mecanico', new_mecanico_path %>
</div>

app/views/mecanicos/new.html.erb
<div class="panel panel-primary">

<h1>INGRESE NUEVO MECANICO</h1>

<%= render 'form' %>

<%= link_to 'ATRAS', mecanicos_path %>
</div>

app/views/mecanicos/show.html.erb
<div class="panel panel-primary">
<h2>MECANICO A CARGO</h2>
<p>
<h3>Nombre  : <%= @mecanico.nombre %></h3>
<h3>Apellido: <%= @mecanico.apellido %></h3>
<br>
<h2>ESPECIALIDAD Y LUGAR:</h2>
<% @especialidads.each do |especialidad| %>
<strong>Especialidad: </strong>
<%= especialidad.espnombre %>
<strong>Lugar: </strong>
<%= especialidad.esplugar %>
<br>
<% end %>
<br>
<%= link_to 'EDITAR', edit_mecanico_path(@mecanico) %> |
<%= link_to 'ATRAS', mecanicos_path %>
</div>