config/routes.rb
Rails.application.routes.draw do
  resources :mecanico_especialidads
  resources :especialidads
  resources :mecanicos
  resources :autos
  
  root :to => 'inicio#index'
  get 'inicio/index'

  devise_for :usuarios

end

app/models/auto.rb
class Auto < ActiveRecord::Base
  validates :patente, presence: true
  validates :color,   presence: true
  belongs_to :usuario
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show

  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:patente, :color, :usuario_id)
    end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/views/autos/_form.html.erb
<%= form_for(@auto) do |f| %>
  <% if @auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% @auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Patente %><br>
    <%= f.text_field :patente %>
  </div>
  <div class="field">
    <%= f.label :Color %><br>
    <%= f.text_field :color %>
</div>
<%= f.hidden_field :usuario_id, :value => current_usuario.id   %>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<div class="panel panel-success">
<h1>MODIFICAR PATENTE/COLOR</h1>

<%= render 'form' %>

<%= link_to 'MOSTRAR', @auto %> |
<%= link_to 'ATRAS', autos_path %>
</div>

app/views/autos/index.html.erb
<div class="panel panel-success">

<h1>LISTA DE AUTOS</h1>

<table class=" table table-bordered table-hover">
  <thead>
    <tr>
      <th>PATENTE</th>
      <th>COLOR</th>
      <th>USUARIO</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autos.each do |auto| %>
      <tr>
        <td><%= auto.patente %></td>
        <td><%= auto.color %></td>
        <td><%= auto.usuario.email %></td>
        <td><%= link_to 'MOSTRAR', auto %></td>
        <% if current_usuario.email == auto.usuario.email  %>
        <td><%= link_to 'MODIFICAR', edit_auto_path(auto) %></td>
        <td><%= link_to 'ELIMINAR', auto, method: :delete, data: { confirm: 'SE ELIMINARA DEL SISTEMA' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'NUEVA PATENTE Y COLOR', new_auto_path %>
</div>

app/views/autos/new.html.erb
<div class="panel panel-success">
<h1>NUEVA PATENTE/COLOR</h1>

<%= render 'form' %>

<%= link_to 'ATRAS', autos_path %>
</div>

app/views/autos/show.html.erb
<div class="panel panel-success">

<h2>PATENTE/COLOR</h2>
<p>
<strong>PATENTE: <strong>
<%= @auto.patente%>
<strong>COLOR: <strong>
<%= @auto.color %>
<strong>USUARIO: <strong>
<%= @auto.usuario.email %>

<br>
<% if current_usuario.email == @auto.usuario.email  %>
<%= link_to 'Edit', edit_auto_path(@auto) %> |
<% end %>
<br>
<%= link_to 'MODIFICAR', edit_auto_path(@auto) %> |
<%= link_to 'ATRAS', autos_path %>
</div>